---
language: ruby
sudo: false
cache: bundler

rvm:
  - '2.2.6'
  - '2.3.3'
  - 'ruby-head'

env:
  - DB=sqlite     RAILS='~> 5.0'
  - DB=postgresql RAILS='~> 5.0'
  - DB=mysql      RAILS='~> 5.0'

matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: 2.2.6
      env: DB=mysql RAILS='4.2'
  include:
    - rvm: 2.2.6
      env: DB=sqlite RAILS='~> 4.2'

before_script:
  # - mysql -e 'create database myapp_test'
  # - psql -c 'create database myapp_test' -U postgres
  - bundle exec rake dummy:setup
  - bundle exec rake app:db:create
  - bundle exec rake app:db:migrate
  - bundle exec rake app:db:migrate RAILS_ENV=test

script:
  - bundle exec rake test

